osmlab/osmlint

- validators/bridgeOnNode/map.js
- validators/filterUsers/map.js
- validators/missingHighwaysUS/map.js
- validators/missingLayerBridges/map.js
- validators/untaggedWays/map.js
> add _osmlint property to each feature

- index.js
- test/test.js
- validators/selfIntersecting/index.js
- validators/selfIntersecting/map.js
Good result! https://github.com/osmlab/osmlint/issues/25
Merge this branch
> Self intersecting

- .eslintrc
- cli.js
- index.js
- test/test.js
- validators/bridgeOnNode/index.js
- validators/bridgeOnNode/map.js
- validators/filterDate/index.js
- validators/filterDate/map.js
- validators/filterUsers/index.js
- validators/filterUsers/map.js
- validators/filterUsers/users.json
- validators/missingHighwaysUS/index.js
- validators/missingHighwaysUS/map.js
- validators/missingLayerBridges/index.js
- validators/missingLayerBridges/map.js
- validators/selfIntersecting/index.js
- validators/selfIntersecting/map.js
- validators/unclosedWays/index.js
- validators/unclosedWays/map.js
- validators/unclosedWays/value_area.js
- validators/untaggedWays/index.js
- validators/untaggedWays/map.js
- Added .eslintrc file
- Modify files to pass ESLint validations
> Validate with Eslint

- validators/filterUsers/map.js
- validators/missingHighwaysUS/map.js
- validators/missingLayerBridges/map.js
- validators/selfIntersecting/map.js
- validators/unclosedWays/map.js
- Remove un-needed parentheses
- Rename some variables to be a bit nicer
> minor stylistic changes

- index.js
- package.json
- test/test.js
- validators/crossingHighways/index.js
- validators/crossingHighways/map.js
Crossing highways is working fine:  relative to : https://github.com/osmlab/osmlint/issues/31#issuecomment-172001446
cc. @geohacker @batpad @maning
> Crossinghighways

- validators.txt
>  Add docs for missing linters

- validators/nodeEndingNearHighway/map.js
Fixing to work with MultiLineString and add  `type= major` or `type=minor` for the output. 
cc @geohacker @batpad @maning
> Unconnected major and minor

- validators/bridgeOnNode/README.md
- validators/crossingHighways/README.md
- validators/crossingWaterwaysHighways/README.md
- validators/filterDate/README.md
- validators/filterUsers/README.md
- validators/islandsHighways/README.md
- validators/missingHighwaysUS/README.md
- validators/missingLayerBridges/README.md
- validators/overlapHighways/README.md
- validators/selfIntersectingHighways/README.md
- validators/unclosedWays/README.md
- validators/unconnectedHighways/README.md
- validators/untaggedWays/README.md
> fix errors in readme. simplify.

- index.js
- test/test.js
- validators/impossibleAngle/README.md
- validators/impossibleAngle/index.js
- validators/impossibleAngle/map.js
From : https://github.com/osmlab/osmlint/issues/83
Time : 10 seg for Peru on my laptop.
@maning, could check the result? https://gist.github.com/anonymous/5fa5095d11c61bb3f1c2906ef4438d2f
@geohacker @batpad  can you take look on code, to merge in master? 
cc. @aaronlidman @planemad
> Impossibleangle

- validators/impossibleAngle/map.js
minor changes , support for MultiLineString
> support multilineString

- test/test.js
- validators/crossingHighways/map.js
- validators/impossibleAngle/map.js
- validators/islandsHighways/map.js
- validators/overlapHighways/map.js
The change here is to avoid the path and service roads to run faster the validation, and focus on minor unclassified, residential, living streets and road. in minor classification.
> comment the services roads

- index.js
- package.json
- test/test.js
- validators/tigerDelta/README.md
- validators/tigerDelta/index.js
- validators/tigerDelta/map.js
from https://github.com/osmlab/osmlint/issues/84
cc. @geohacker @batpad @maning @planemad
> Tiger delta

- validators/crossingWaterwaysHighways/map.js
Classification of roads and add support for MultiLineString
cc. @geohacker
> Classifications of crossingWaterwaysHighways

- validators/impossibleOneWays/map.js
avoid `highway=service` and `highway=road `
> comment service and road

- validators/turnLanes/map.js
from https://github.com/osmlab/osmlint/issues/109#issuecomment-225330660
> fix turnlanes

- validators/turnLanes/map.js
detect `none` which are whit conjunction with other signs
> Fix turns lanes

- validators/selfIntersectingHighways/map.js
from https://github.com/osmlab/osmlint/issues/131
> fixing false positive and rename variables

- validators/missingLayerBridges/map.js
https://github.com/osmlab/osmlint/issues/132
> false positive bidge=no

- validators/mixedLayer/map.js
from https://github.com/osmlab/osmlint/issues/135
> remove false positive from mixed layer

- validators/crossingWaterwaysHighways/map.js
- validators/doubledPlaces/README.md
- validators/doubledPlaces/index.js
- validators/doubledPlaces/map.js
@Rub21  I've added `waterway=derelict_canal` to being filtered.
> Derelict canal

- validators/01_dir_template/README.md
- validators/01_dir_template/index.js
- validators/01_dir_template/map.js
I am adding a  template   to easy start  on write a validator.
cc. @geohacker @maning @planemad
> add template to start a validator

- validators/crossingHighwaysBuildings/map.js
> fix minor issues in crossing building and highways

- validators/unconnectedHighways/map.js
> Fix duplicate detection of points  in MultiLineString case.

- test/misspelledTags.test.js
- validators/misspelledTags/value_area.js
I reconsidered all attributes.
@Rub21
> Updating misspelled

- validators/misspelledTags/value_area.js
> deleting stop attributes

- package.json
> updating dependencie of data team

- validators/invalidTurnLanes/map.js
> update turnales detection

- test/crossingBuildings.test.js
- validators/crossingBuildings/map.js
> Fix crossing buildings bbox issue
